import { createContext, useContext, useState, useEffect, useCallback, ReactNode } from 'react'
import { docTranslations } from '../constants/docTranslations'

export type Language = 'en' | 'zh'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const STORAGE_KEY = 'dockpull-language'

const translations: Record<Language, Record<string, string>> = {
  en: {
    'login.brandTitle': 'DockerPull',
    'login.brandDesc': 'A lightweight Docker image management system for pulling and organizing container images with ease',
    'login.title': 'Welcome Back',
    'login.subtitle': 'Sign in to your account to continue',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.usernamePlaceholder': 'Enter your username',
    'login.passwordPlaceholder': 'Enter your password',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot password?',
    'login.submit': 'Sign In',
    'login.submitting': 'Signing in...',
    'login.or': 'OR',
    'login.sso': 'Sign in with SSO',
    'login.newUser': 'New user?',
    'login.requestAccess': 'Request access',
    'login.invalidCredentials': 'Invalid username or password',
    'login.error': 'An error occurred. Please try again.',

    'nav.overview': 'Overview',
    'nav.images': 'Images',
    'nav.localImages': 'Local',
    'nav.logs': 'Logs',
    'nav.settings': 'Settings',
    'nav.docs': 'Docs',
    'nav.support': 'Support',
    'search.placeholder': 'Search...',
    'search.noResults': 'No results found for',
    'search.hint': 'Type to start searching',
    'theme.light': 'Light Theme',
    'theme.dark': 'Dark Theme',
    'lang.switch': 'Switch language',
    'lang.en': 'English',
    'lang.zh': '中文',

    'settings.title': 'Settings',
    'settings.tab.account': 'Account',
    'settings.tab.export': 'Export',
    'settings.tab.tokens': 'Tokens',
    'settings.tab.webhook': 'Webhook',
    'settings.account.title': 'Account Settings',
    'settings.account.subtitle': 'Manage your account credentials and password.',
    'settings.export.title': 'Export Settings',
    'settings.export.subtitle': 'Configure export path, platform, and pull behavior.',
    'settings.tokens.title': 'Access Tokens',
    'settings.tokens.subtitle': 'Configure authentication tokens for container registries.',
    'settings.webhook.title': 'Webhook Notifications',
    'settings.webhook.subtitle': 'Configure notifications for pull completion and failures.',
    'settings.loading': 'Loading configuration...',
    'settings.save': 'Save',
    'settings.saving': 'Saving...',
    'settings.saved': 'Saved',
    'settings.failed': 'Failed',
    'settings.test': 'Test',
    'settings.testing': 'Testing...',
    'settings.sent': 'Sent',
    'settings.password.success': 'Password changed successfully',
    'settings.password.minLength': 'New password must be at least 6 characters',
    'settings.password.mismatch': 'New passwords do not match',
    'settings.password.old': 'Old Password',
    'settings.password.oldHint': 'Enter your current password.',
    'settings.password.oldPlaceholder': 'Enter old password',
    'settings.password.new': 'New Password',
    'settings.password.newHint': 'New password must be at least 6 characters.',
    'settings.password.newPlaceholder': 'Enter new password',
    'settings.password.confirm': 'Confirm New Password',
    'settings.password.confirmHint': 'Re-enter your new password to confirm.',
    'settings.password.confirmPlaceholder': 'Confirm new password',
    'settings.export.directory': 'Export Directory',
    'settings.export.directoryHint': 'Directory where pulled images are saved.',
    'settings.export.browse': 'Browse',
    'settings.export.platform': 'Default Platform',
    'settings.export.platformHint': 'Target architectures for image pulls.',
    'settings.export.concurrent': 'Concurrent Pulls',
    'settings.export.concurrentHint': 'Max simultaneous pulls (1-10).',
    'settings.export.gzip': 'Gzip Compression',
    'settings.export.gzipHint': 'Compression level (1-9).',
    'settings.export.retries': 'Max Retries',
    'settings.export.retriesHint': 'Set 0 for unlimited retries.',
    'settings.export.retryInterval': 'Retry Interval (s)',
    'settings.export.retryIntervalHint': 'Seconds between each attempt.',
    'settings.export.runtime': 'Container Runtime',
    'settings.export.runtimeHint': 'Select Docker or Podman as the container runtime engine.',
    'settings.export.runtimeDocker': 'Docker',
    'settings.export.runtimePodman': 'Podman',
    'settings.export.runtimeDetected': 'Runtime auto-detected',
    'settings.export.runtimeDetectFailed': 'Failed to detect runtime',
    'settings.export.runtimeRefresh': 'Refresh detection',
    'settings.export.runtimeNoneAvailable': 'No container runtime detected. Please install Docker or Podman.',
    'settings.webhook.enable': 'Enable Webhooks',
    'settings.webhook.enableHint': 'Send a POST request when pulls finish.',
    'settings.webhook.enabled': 'Enabled',
    'settings.webhook.disabled': 'Disabled',
    'settings.webhook.type': 'Webhook Type',
    'settings.webhook.typeHint': 'Platform to deliver notifications to.',
    'settings.webhook.url': 'Webhook URL',
    'settings.webhook.urlHint': 'Endpoint to POST notification payloads.',
    'settings.tokens.none': 'No registry tokens configured',
    'settings.tokens.add': 'Add Registry Token',
    'settings.tokens.addAnother': 'Add Another Registry',
    'settings.tokens.select': 'Select a registry to add',
    'settings.tokens.allConfigured': 'All registries are already configured',
    'settings.tokens.remove': 'Remove',
    'settings.tokens.close': 'Close',

    'token.dockerhub.name': 'Docker Hub',
    'token.dockerhub.hint': 'Username and access token for Docker Hub (hub.docker.com). Create token at Account Settings > Security.',
    'token.dockerhub.username': 'Username',
    'token.dockerhub.token': 'Access token',
    'token.ghcr.name': 'GitHub Container Registry (ghcr.io)',
    'token.ghcr.hint': 'Personal access token with read:packages scope. Required even for public images.',
    'token.ghcr.token': 'ghp_xxxxxxxxxxxx',
    'token.quay.name': 'Quay.io',
    'token.quay.hint': 'Access token for Quay.io registry. Create robot account or use OAuth token.',
    'token.quay.token': 'Quay access token',
    'token.acr.name': 'Alibaba Container Registry (acr)',
    'token.acr.hint': 'Username and password for Alibaba Cloud Container Registry (cr.aliyun.com).',
    'token.acr.username': 'Username',
    'token.acr.password': 'Password',
    'token.ecr.name': 'AWS ECR',
    'token.ecr.hint': 'AWS credentials for Elastic Container Registry. Region defaults to us-east-1.',
    'token.ecr.accessKey': 'Access Key ID',
    'token.ecr.secretKey': 'Secret Access Key',
    'token.ecr.region': 'Region (e.g., us-east-1)',
'token.gar.name': 'Google Artifact Registry (gar)',
    'token.gar.hint': 'Service account JSON key or OAuth token for Google Artifact Registry.',
    'token.gar.token': 'Google Cloud token or JSON key',
    
    'token.harbor.name': 'Harbor',
    'token.harbor.hint': 'Private Harbor registry. URL, username, password required. TLS certificate optional for self-signed certs.',
    'token.harbor.url': 'Harbor URL',
    'token.harbor.username': 'Username',
    'token.harbor.password': 'Password',
    'token.harbor.tlsCert': 'TLS Certificate',
    'token.harbor.optional': 'optional',
    'token.harbor.paste': 'Paste',
    'token.harbor.upload': 'Upload',
    'token.harbor.certPlaceholder': 'Paste certificate content here...',
    'token.harbor.selectFile': 'Select certificate file',
    'token.harbor.certLoaded': 'Certificate loaded',
    
    'token.tencentcloud.name': 'Tencent Cloud Container Registry',
    'token.tencentcloud.hint': 'Username and password for Tencent Cloud Container Registry.',
    'token.tencentcloud.username': 'Username',
    'token.tencentcloud.password': 'Password',
    
    'token.huaweicloud.name': 'Huawei Cloud Container Registry',
    'token.huaweicloud.hint': 'Username and password for Huawei Cloud Software Repository for Container.',
    'token.huaweicloud.username': 'Username',
    'token.huaweicloud.password': 'Password',
    
    'toast.imageNoArm64': 'Image does not support linux/arm64, pulling linux/amd64 only',
    'toast.unableVerify': 'Unable to verify image architecture, continuing with selected platforms',
    'toast.tasksSkipped': '{count} task(s) skipped (already exists), {added} task(s) added',
    'toast.tasksAdded': 'Added {count} image task(s)',
    'toast.authRequired': '{registry} requires authentication. Check Settings > Tokens',

    'status.pending': 'Pending',
    'status.pulling': 'Pulling',
    'status.success': 'Success',
    'status.failed': 'Failed',

    'logs.title': 'Logs',
    'logs.refresh': 'Refresh',
    'logs.searchPlaceholder': 'Search logs...',
    'logs.allPlatforms': 'All Platforms',
    'logs.allImages': 'All Images',
    'logs.allActions': 'All Actions',
    'logs.clearFilters': 'Clear Filters',
    'logs.loading': 'Loading...',
    'logs.empty.title': 'No logs found',
    'logs.empty.desc': 'Start pulling images to see activity logs',
    'logs.empty.noLogs': 'No logs match your search',
    'logs.table.time': 'Time',
    'logs.table.image': 'Image',
    'logs.table.action': 'Action',
    'logs.table.message': 'Message',

    'action.created': 'Created',
    'action.updated': 'Updated',
    'action.pulling': 'Pulling',
    'action.success': 'Success',
    'action.failed': 'Failed',
    'action.exporting': 'Exporting',
    'action.exported': 'Exported',
    'action.changed': 'Changed',
    'action.localDeleting': 'Deleting',
    'action.localDeleted': 'Deleted',

    'platform.amd64': 'AMD64',
    'platform.arm64': 'ARM64',

    'stats.title': 'Overview',
    'stats.total': 'Total',
    'stats.totalDesc': 'Total number of images',
    'stats.success': 'Success',
    'stats.successDesc': 'Successfully pulled images',
    'stats.failed': 'Failed',
    'stats.failedDesc': 'Failed pull attempts',
    'stats.pending': 'Pending',
    'stats.pendingDesc': 'Images queued for processing',
    'stats.successRate': 'Success Rate',
    'stats.successRateDesc': 'Based on {count} total tasks',
    'stats.legend.success': 'Success',
    'stats.legend.failed': 'Failed',
    'stats.legend.pending': 'Pending',

    'images.title': 'Images',
    'images.add': 'Add',
    'images.loading': 'Loading...',
    'images.exported': 'Exported',
    'images.retry': 'Retry',
    'images.download': 'Download',
    'images.delete': 'Delete',
    'images.empty.title': 'Start Pulling Container Images',
    'images.empty.desc1': 'Add images from Docker Hub, GitHub, Quay, Alibaba, AWS, Google, Harbor and more.',
    'images.empty.desc2': 'Support multi-platform pulls with automatic retry and export.',
    'images.table.image': 'Image',
    'images.table.platform': 'Platform',
    'images.table.status': 'Status',
    'images.table.retries': 'Retries',
    'images.table.exportStatus': 'Export Status',
    'images.table.created': 'Created',
    'images.table.actions': 'Actions',
    
    'copy.copied': 'Copied!',
    'copy.copyName': 'Copy image name',

    'user.admin': 'Administrator',
    'user.clickChange': 'Click avatar to change',
    'user.logout': 'Log out',
    'user.uploadValid': 'Please upload a valid image file (JPEG, PNG, GIF, WebP, BMP)',
    'user.fileSize': 'File size must be less than 10MB',

    'dirPicker.title': 'Select Directory',
    'dirPicker.subtitle': 'Choose where to save exported images',
    'dirPicker.quickAccess': 'Quick Access',
    'dirPicker.name': 'Name',
    'dirPicker.dateModified': 'Date modified',
    'dirPicker.type': 'Type',
    'dirPicker.cancel': 'Cancel',
    'dirPicker.select': 'Select',
    'dirPicker.loadFailed': 'Failed to load directory',

    'localImages.title': 'Local',
    'localImages.refresh': 'Refresh',
    'localImages.loading': 'Loading local images...',
    'localImages.loadFailed': 'Failed to load local images',
    'localImages.table.image': 'Image',
    'localImages.table.arch': 'Arch',
    'localImages.table.size': 'Size',
    'localImages.table.created': 'Created',
    'localImages.table.actions': 'Actions',
    'localImages.export': 'Export',
    'localImages.delete': 'Delete',
    'localImages.exportSuccess': 'Exported {image} to {path}',
    'localImages.exportFailed': 'Failed to export {image}',
    'localImages.deleteSuccess': 'Deleted {image}',
    'localImages.deleteFailed': 'Failed to delete {image}',
    'localImages.deleteConfirm': 'Are you sure you want to delete {image}? This cannot be undone.',
    'localImages.empty.title': 'No local images found',
    'localImages.empty.desc': 'Pull images first to manage them locally',

    'modal.addImage': 'Add Image',
    'modal.batchMode': 'Batch Mode',
    'modal.images': 'Images',
    'modal.image': 'Image',
    'modal.platforms': 'Platforms',
    'modal.autoExport': 'Auto Export',
    'modal.cancel': 'Cancel',
    'modal.saving': 'Saving...',

    'unsaved.title': 'Unsaved Changes',
    'unsaved.message': 'You have unsaved changes in your settings. Do you want to save them before leaving?',
    'unsaved.save': 'Save',
    'unsaved.discard': 'Discard',
    'unsaved.stay': 'Stay',
    'unsaved.saveConfirm': 'Save Changes',
    'unsaved.discardConfirm': 'Discard Changes',

    ...docTranslations.en,
  },
  zh: {
    'login.brandTitle': 'DockerPull',
    'login.brandDesc': 'Docker 镜像拉取与导出管理工具',
    'login.title': '欢迎回来',
    'login.subtitle': '登录您的账户以继续',
    'login.username': '用户名',
    'login.password': '密码',
    'login.usernamePlaceholder': '请输入用户名',
    'login.passwordPlaceholder': '请输入密码',
    'login.rememberMe': '记住我',
    'login.forgotPassword': '忘记密码？',
    'login.submit': '登录',
    'login.submitting': '登录中...',
    'login.or': '或',
    'login.sso': '使用 SSO 登录',
    'login.newUser': '新用户？',
    'login.requestAccess': '申请访问权限',
    'login.invalidCredentials': '用户名或密码错误',
    'login.error': '发生错误，请重试',

    'nav.overview': '概览',
    'nav.images': '镜像',
    'nav.localImages': '本地',
    'nav.logs': '日志',
    'nav.settings': '设置',
    'nav.docs': '文档',
    'nav.support': '支持',
    'search.placeholder': '搜索...',
    'search.noResults': '未找到相关结果',
    'search.hint': '输入开始搜索',
    'theme.light': '浅色主题',
    'theme.dark': '深色主题',
    'lang.switch': '切换语言',
    'lang.en': 'English',
    'lang.zh': '中文',

    'settings.title': '设置',
    'settings.tab.account': '账户',
    'settings.tab.export': '导出',
    'settings.tab.tokens': '令牌',
    'settings.tab.webhook': 'Webhook',
    'settings.account.title': '账户设置',
    'settings.account.subtitle': '管理您的账户凭证和密码。',
    'settings.export.title': '导出设置',
    'settings.export.subtitle': '配置导出路径、平台和拉取行为。',
    'settings.tokens.title': '访问令牌',
    'settings.tokens.subtitle': '配置容器镜像仓库的身份验证令牌。',
    'settings.webhook.title': 'Webhook 通知',
    'settings.webhook.subtitle': '配置拉取完成和失败的通知。',
    'settings.loading': '加载配置中...',
    'settings.save': '保存',
    'settings.saving': '保存中...',
    'settings.saved': '已保存',
    'settings.failed': '失败',
    'settings.test': '测试',
    'settings.testing': '测试中...',
    'settings.sent': '已发送',
    'settings.password.success': '密码修改成功',
    'settings.password.minLength': '新密码至少需要6个字符',
    'settings.password.mismatch': '两次输入的新密码不一致',
    'settings.password.old': '旧密码',
    'settings.password.oldHint': '输入您当前的密码。',
    'settings.password.oldPlaceholder': '输入旧密码',
    'settings.password.new': '新密码',
    'settings.password.newHint': '新密码至少需要6个字符。',
    'settings.password.newPlaceholder': '输入新密码',
    'settings.password.confirm': '确认新密码',
    'settings.password.confirmHint': '再次输入新密码以确认。',
    'settings.password.confirmPlaceholder': '确认新密码',
    'settings.export.directory': '导出目录',
    'settings.export.directoryHint': '拉取的镜像保存目录。',
    'settings.export.browse': '浏览',
    'settings.export.platform': '默认平台',
    'settings.export.platformHint': '镜像拉取的目标架构。',
    'settings.export.concurrent': '并发拉取数',
    'settings.export.concurrentHint': '最大同时拉取数（1-10）。',
    'settings.export.gzip': 'Gzip 压缩',
    'settings.export.gzipHint': '压缩级别（1-9）。',
    'settings.export.retries': '最大重试次数',
    'settings.export.retriesHint': '设为0表示无限重试。',
    'settings.export.retryInterval': '重试间隔（秒）',
    'settings.export.retryIntervalHint': '每次重试之间的秒数。',
    'settings.export.runtime': '容器运行时',
    'settings.export.runtimeHint': '选择 Docker 或 Podman 作为容器运行时引擎。',
    'settings.export.runtimeDocker': 'Docker',
    'settings.export.runtimePodman': 'Podman',
    'settings.export.runtimeDetected': '自动检测到运行时',
    'settings.export.runtimeDetectFailed': '运行时检测失败',
    'settings.export.runtimeRefresh': '刷新检测',
    'settings.export.runtimeNoneAvailable': '未检测到容器运行时，请安装 Docker 或 Podman。',
    'settings.webhook.enable': '启用 Webhooks',
    'settings.webhook.enableHint': '拉取完成时发送 POST 请求。',
    'settings.webhook.enabled': '已启用',
    'settings.webhook.disabled': '已禁用',
    'settings.webhook.type': 'Webhook 类型',
    'settings.webhook.typeHint': '接收通知的平台。',
    'settings.webhook.url': 'Webhook URL',
    'settings.webhook.urlHint': '接收通知的 POST 端点。',
    'settings.tokens.none': '未配置任何镜像仓库令牌',
    'settings.tokens.add': '添加镜像仓库令牌',
    'settings.tokens.addAnother': '添加其他仓库',
    'settings.tokens.select': '选择要添加的镜像仓库：',
    'settings.tokens.allConfigured': '所有镜像仓库都已配置',
    'settings.tokens.remove': '移除',
    'settings.tokens.close': '关闭',

    'token.dockerhub.name': 'Docker Hub',
    'token.dockerhub.hint': 'Docker Hub 的用户名和访问令牌。在账户设置 > 安全中创建令牌。',
    'token.dockerhub.username': '用户名',
    'token.dockerhub.token': '访问令牌',
    'token.ghcr.name': 'GitHub Container Registry (ghcr.io)',
    'token.ghcr.hint': '具有 read:packages 权限的个人访问令牌。即使是公开镜像也需要。',
    'token.ghcr.token': 'ghp_xxxxxxxxxxxx',
    'token.quay.name': 'Quay.io',
    'token.quay.hint': 'Quay.io 镜像仓库的访问令牌。创建机器人账户或使用 OAuth 令牌。',
    'token.quay.token': 'Quay 访问令牌',
    'token.acr.name': '阿里云容器镜像服务',
    'token.acr.hint': '阿里云容器镜像服务 的用户名和密码。',
    'token.acr.username': '用户名',
    'token.acr.password': '密码',
    'token.ecr.name': 'AWS ECR',
    'token.ecr.hint': 'AWS ECR 的凭证。默认区域为 us-east-1。',
    'token.ecr.accessKey': 'Access Key ID',
    'token.ecr.secretKey': 'Secret Access Key',
    'token.ecr.region': '区域（例如：us-east-1）',
'token.gar.name': 'Google Artifact Registry',
    'token.gar.hint': 'Google Artifact Registry 的服务账户 JSON 密钥或 OAuth 令牌。',
    'token.gar.token': 'Google Cloud 令牌或 JSON 密钥',
    
    'token.harbor.name': 'Harbor',
    'token.harbor.hint': '私有 Harbor 仓库。URL、用户名、密码必填。TLS 证书可选，用于自签名证书。',
    'token.harbor.url': 'Harbor 地址',
    'token.harbor.username': '用户名',
    'token.harbor.password': '密码',
    'token.harbor.tlsCert': 'TLS 证书',
    'token.harbor.optional': '可选',
    'token.harbor.paste': '粘贴',
    'token.harbor.upload': '上传',
    'token.harbor.certPlaceholder': '在此粘贴证书内容...',
    'token.harbor.selectFile': '选择证书文件',
    'token.harbor.certLoaded': '证书已加载',
    
    'token.tencentcloud.name': '腾讯云容器仓库',
    'token.tencentcloud.hint': '腾讯云容器仓库的用户名和密码。',
    'token.tencentcloud.username': '用户名',
    'token.tencentcloud.password': '密码',
    
    'token.huaweicloud.name': '华为云容器仓库',
    'token.huaweicloud.hint': '华为云容器软件仓库的用户名和密码。',
    'token.huaweicloud.username': '用户名',
    'token.huaweicloud.password': '密码',
    
    'toast.imageNoArm64': '镜像不支持 linux/arm64，仅拉取 linux/amd64',
    'toast.unableVerify': '无法验证镜像架构，继续使用所选平台',
    'toast.tasksSkipped': '{count} 个任务跳过（已存在），{added} 个任务已添加',
    'toast.tasksAdded': '已添加 {count} 个镜像任务',
    'toast.authRequired': '{registry} 需要认证。请检查设置 > 令牌',

    'status.pending': '待处理',
    'status.pulling': '拉取中',
    'status.success': '成功',
    'status.failed': '失败',

    'logs.title': '日志',
    'logs.refresh': '刷新',
    'logs.searchPlaceholder': '搜索日志...',
    'logs.allPlatforms': '所有平台',
    'logs.allImages': '所有镜像',
    'logs.allActions': '所有操作',
    'logs.clearFilters': '清除筛选',
    'logs.loading': '加载中...',
    'logs.empty.title': '暂无日志',
    'logs.empty.desc': '开始拉取镜像以查看活动日志',
    'logs.empty.noLogs': '没有匹配的日志',
    'logs.table.time': '时间',
    'logs.table.image': '镜像',
    'logs.table.action': '操作',
    'logs.table.message': '消息',

    'action.created': '创建',
    'action.updated': '更新',
    'action.pulling': '拉取中',
    'action.success': '成功',
    'action.failed': '失败',
    'action.exporting': '导出中',
    'action.exported': '已导出',
    'action.changed': '已更改',
    'action.localDeleting': '删除中',
    'action.localDeleted': '已删除',

    'platform.amd64': 'AMD64',
    'platform.arm64': 'ARM64',

    'stats.title': '概览',
    'stats.total': '总数',
    'stats.totalDesc': '镜像总数量',
    'stats.success': '成功',
    'stats.successDesc': '成功拉取的镜像',
    'stats.failed': '失败',
    'stats.failedDesc': '拉取失败的镜像',
    'stats.pending': '待处理',
    'stats.pendingDesc': '队列中的镜像任务',
    'stats.successRate': '成功率',
    'stats.successRateDesc': '基于 {count} 个总任务',
    'stats.legend.success': '成功',
    'stats.legend.failed': '失败',
    'stats.legend.pending': '待处理',

    'images.title': '镜像',
    'images.add': '添加',
    'images.loading': '加载中...',
    'images.exported': '已导出',
    'images.retry': '重试',
    'images.download': '下载',
    'images.delete': '删除',
    'images.empty.title': '开始拉取容器镜像',
    'images.empty.desc1': '支持从 Docker Hub、GitHub、Quay、阿里云、AWS、Google、Harbor 等仓库拉取镜像，',
    'images.empty.desc2': '支持多平台并行拉取、自动重试和导出。',
    'images.table.image': '镜像',
    'images.table.platform': '平台',
    'images.table.status': '状态',
    'images.table.retries': '重试次数',
    'images.table.exportStatus': '导出状态',
    'images.table.created': '创建时间',
    'images.table.actions': '操作',
    
    'copy.copied': '已复制！',
    'copy.copyName': '复制镜像名称',

    'user.admin': '管理员',
    'user.clickChange': '点击头像更换',
    'user.logout': '退出登录',
    'user.uploadValid': '请上传有效的图片文件（JPEG、PNG、GIF、WebP、BMP）',
    'user.fileSize': '文件大小不能超过10MB',

    'dirPicker.title': '选择目录',
    'dirPicker.subtitle': '选择导出镜像的保存位置',
    'dirPicker.quickAccess': '快速访问',
    'dirPicker.name': '名称',
    'dirPicker.dateModified': '修改日期',
    'dirPicker.type': '类型',
    'dirPicker.cancel': '取消',
    'dirPicker.select': '选择',
    'dirPicker.loadFailed': '加载目录失败',

    'localImages.title': '本地',
    'localImages.refresh': '刷新',
    'localImages.loading': '加载本地镜像中...',
    'localImages.loadFailed': '加载本地镜像失败',
    'localImages.table.image': '镜像',
    'localImages.table.arch': '架构',
    'localImages.table.size': '大小',
    'localImages.table.created': '创建时间',
    'localImages.table.actions': '操作',
    'localImages.export': '导出',
    'localImages.delete': '删除',
    'localImages.exportSuccess': '已将 {image} 导出至 {path}',
    'localImages.exportFailed': '导出 {image} 失败',
    'localImages.deleteSuccess': '已删除 {image}',
    'localImages.deleteFailed': '删除 {image} 失败',
    'localImages.deleteConfirm': '确定要删除 {image} 吗？此操作无法撤销。',
    'localImages.empty.title': '未找到本地镜像',
    'localImages.empty.desc': '请先拉取镜像再进行本地管理',

    'modal.addImage': '添加镜像',
    'modal.batchMode': '批量模式',
    'modal.images': '镜像列表',
    'modal.image': '镜像',
    'modal.platforms': '平台',
    'modal.autoExport': '自动导出',
    'modal.cancel': '取消',
    'modal.saving': '保存中...',

    'unsaved.title': '未保存的更改',
    'unsaved.message': '您的设置中有未保存的更改。在离开前是否要保存？',
    'unsaved.save': '保存',
    'unsaved.discard': '放弃',
    'unsaved.stay': '留在页面',
    'unsaved.saveConfirm': '保存更改',
    'unsaved.discardConfirm': '放弃更改',

    ...docTranslations.zh,
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem(STORAGE_KEY)
    if (stored === 'en' || stored === 'zh') {
      document.documentElement.setAttribute('data-lang', stored)
      document.documentElement.lang = stored === 'zh' ? 'zh-CN' : 'en'
      return stored
    }
    const browserLang = navigator.language.toLowerCase()
    const initialLang = browserLang.startsWith('zh') ? 'zh' : 'en'
    document.documentElement.setAttribute('data-lang', initialLang)
    document.documentElement.lang = initialLang === 'zh' ? 'zh-CN' : 'en'
    return initialLang
  })

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language)
    document.documentElement.setAttribute('data-lang', language)
    document.documentElement.lang = language === 'zh' ? 'zh-CN' : 'en'
  }, [language])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
  }

  const t = useCallback((key: string): string => {
    return translations[language][key] || key
  }, [language])

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used within LanguageProvider')
  return context
}